version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - "32768:6379"


  docs_api:
    build: ./docs_api
    ports:
      - "5000:5000"
    environment:
      ENV_VAR: DEV
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER : test
      POSTGRES_PASSWORD: test
    ports:
      - 5444:5432
