PROJECT_NAME: DocumentsAPP
PRJ_HOST: 127.0.0.1
PRJ_PORT: 5000

LOG_LEVEL: debug

POSTGRES_SERVER: localhost
POSTGRES_PORT: 5432
POSTGRES_USER: test
POSTGRES_PASSWORD: test
POSTGRES_DB: db_test
