SECRET_KEY: 09d25e094faa6ca25sd5kg6b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
ALGORITHM: HS256
ACCESS_TOKEN_EXPIRE_MINUTES: 30
FIRST_SUPERUSER: super
FIRST_SUPERUSER_PASSWORD: super
PROJECT_NAME: DocumentsAPP
PRJ_HOST: 127.0.0.1
PRJ_PORT: 5000

LOG_LEVEL: debug
DB_SCHEMA: public

POSTGRES_SERVER: localhost
POSTGRES_PORT: 5444
POSTGRES_USER: test
POSTGRES_PASSWORD: test
POSTGRES_DB: db_test

BLOCKED_EXTS: exe,xls

REDIS_HOST: localhost
REDIS_PORT: 32768
SESSION_EXPIRE: 60
SSID: session_id
